// `npm run setup` — getting a new machine ready, Windows included.
//
// It does everything that can be done without someone else's credentials:
// generates this machine's WireGuard key pair and writes its wg0.conf. What it
// cannot do (authorize the key on the VPS, create the DNS record) it prints as
// ready-to-copy commands, with the values already substituted.
//
// It is idempotent: if the tunnel is already configured it regenerates nothing,
// because doing so would invalidate the key the VPS has already authorized.

import { execFileSync } from 'node:child_process'
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname } from 'node:path'
import { loadConfig } from '../config.js'
import { confPath, IFACE, parseConfPrivateKey, tunnelState } from './tunnel.js'

const config = loadConfig()
const line = (s = '') => console.log(s)

/** `wg` lives in brew's prefix on macOS and next to wireguard.exe on Windows. */
function wgBinary(): string | null {
  const candidates = process.platform === 'win32'
    ? ['C:\\Program Files\\WireGuard\\wg.exe']
    : ['/opt/homebrew/bin/wg', '/usr/local/bin/wg']
  return candidates.find(existsSync) ?? null
}

function installHint(): string {
  if (process.platform === 'win32') return 'Download and install WireGuard: https://www.wireguard.com/install/'
  if (process.platform === 'darwin') return 'Install it with:  brew install wireguard-tools'
  return 'Install it with your distribution package manager (`wireguard-tools`).'
}

line()
line('🎬 Watchparty machine setup')
line()

// ---------------------------------------------------------------------------
// 1. The relay: is it needed?
// ---------------------------------------------------------------------------
const relayWanted = Boolean(config.streamBaseUrl || config.relayEndpoint)

if (!relayWanted) {
  line('ℹ️  Data-plane relay: not configured, and not needed for local-network use')
  line('   or with the Cloudflare tunnel. If you want it, fill in')
  line('   relayEndpoint / relayPeerPublicKey / relayPeerIp and streamBaseUrl in')
  line('   your config.json and run `npm run setup` again.')
  line()
  line('▶️  Nothing else to do. Run `npm start`.')
  line()
  process.exit(0)
}

const missing = [
  !config.relayEndpoint && 'relayEndpoint',
  !config.relayPeerPublicKey && 'relayPeerPublicKey',
  !config.relayPeerIp && 'relayPeerIp',
  !config.relayLocalIp && 'relayLocalIp',
].filter(Boolean)

if (missing.length > 0) {
  line(`❌ Missing relay configuration: ${missing.join(', ')}`)
  line('   Fill them in where you keep shared defaults (they travel with the repo: none is a secret).')
  line()
  process.exit(1)
}

const wg = wgBinary()
if (!wg) {
  line('❌ WireGuard is not installed on this machine.')
  line(`   ${installHint()}`)
  line('   Then run `npm run setup` again.')
  line()
  process.exit(1)
}
line('✅ WireGuard installed')

// ---------------------------------------------------------------------------
// 2. This machine's keys and wg0.conf
// ---------------------------------------------------------------------------
const path = confPath()
let publicKey: string

if (tunnelState() !== 'unconfigured') {
  // Regenerating here would leave the VPS authorizing a key we no longer use,
  // and the tunnel would go down with no explanation beyond a handshake that
  // never arrives.
  line(`✅ Tunnel already configured at ${path} (left alone)`)
  // Derived from the private key in the file rather than with `wg show`: that
  // needs root on macOS (it reads the control socket in /var/run/wireguard), and
  // nothing here has to ask for privileges.
  const priv = parseConfPrivateKey(readFileSync(path, 'utf8'))
  publicKey = priv
    ? execFileSync(wg, ['pubkey'], { input: priv, encoding: 'utf8' }).trim()
    : '(could not read the key from the .conf)'
} else {
  const privateKey = execFileSync(wg, ['genkey'], { encoding: 'utf8' }).trim()
  publicKey = execFileSync(wg, ['pubkey'], { input: privateKey, encoding: 'utf8' }).trim()

  const conf = `# Local end of the Watchparty relay. Generated by \`npm run setup\`.
[Interface]
Address = ${config.relayLocalIp}/24
PrivateKey = ${privateKey}

[Peer]
PublicKey = ${config.relayPeerPublicKey}
Endpoint = ${config.relayEndpoint}
# ONLY the VPS /32. This is not an outbound VPN: the rest of this machine's
# traffic keeps its usual route.
AllowedIPs = ${config.relayPeerIp}/32
# Required: this host sits behind NAT and the VPS INITIATES the connections
# toward us. Without keepalive the router mapping expires and the VPS loses us
# in the middle of a movie.
PersistentKeepalive = 25
`
  mkdirSync(dirname(path), { recursive: true })
  writeFileSync(path, conf, { mode: 0o600 })
  line(`✅ Keys generated and configuration written to ${path}`)
}

// ---------------------------------------------------------------------------
// 3. What has to be done off this machine
// ---------------------------------------------------------------------------
const [host] = String(config.relayEndpoint).split(':')

line()
line('── One manual step left, on the VPS ─────────────────────────────')
line()
line('   Authorize this machine\'s key (replaces the previous peer: only one')
line('   host at a time, and the VPS reverse_proxy points at a fixed IP):')
line()
line(`   ssh ubuntu@${host} "sudo wg set ${IFACE} peer ${publicKey} allowed-ips ${config.relayLocalIp}/32 && sudo wg-quick save ${IFACE}"`)
line()
if (config.streamBaseUrl) {
  const name = config.streamBaseUrl.replace(/^https?:\/\//, '')
  line(`   And check that ${name} resolves to ${host} with the proxy OFF`)
  line('   (grey-cloud DNS record in Cloudflare). Orange cloud sends video back through the CDN.')
  line()
}
line('────────────────────────────────────────────────────────────────')
line()
line('▶️  Once that is done, `npm start` brings the tunnel up by itself and checks the rest.')
line()
